### ISSUE TITLE
react-hookz/web lint:fix script failing due to ESLint error: unknown environment key "es2022"

### ISSUE THREAD

**Issue by ArttuOll** [react-hookz/eslint-config#116]
Hello everyone!

I'm currently in the process of finalizing my implementation of `useCounter` and almost ready to make a PR to react-hookz/web. However, it seems I am unable to run the required `lint:fix` script. When I run it, I get the following error:

```
Oops! Something went wrong! :(

ESLint: 8.5.0

Error: .eslintrc.js#overrides[0] » @react-hookz/eslint-config/react » ./base » plugin:unicorn/recommended:
        Environment key "es2022" is unknown

    at /usr/local/lib/node_modules/eslint/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:821:23
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateEnvironment (/usr/local/lib/node_modules/eslint/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:815:34)
    at ConfigValidator.validateConfigArray (/usr/local/lib/node_modules/eslint/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:965:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/usr/local/lib/node_modules/eslint/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3886:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/usr/local/lib/node_modules/eslint/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3692:21)
    at FileEnumerator._iterateFilesRecursive (/usr/local/lib/node_modules/eslint/lib/cli-engine/file-enumerator.js:446:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/usr/local/lib/node_modules/eslint/lib/cli-engine/file-enumerator.js:297:49)
    at iterateFiles.next (<anonymous>)
```

This error was produced on the latest `master` of react-hookz/web. ESLint version: 8.5.0, TypeScript version: 4.6.4, Node version 16.13.1, OS: Ubuntu 22.04.

This error seems to stem from es2022 not being supported by eslint as an environment key because it adds no new globals, as discussed [in this issue in the eslint repo](https://github.com/eslint/eslint/issues/15580). In that issue, one suggested solution is to configure eslint like this:
```
{
   "parserOptions": {
      "ecmaVersion": 2022
   },
   "env": {
      "es2021": true
   } 
}
```
that is, enabling the use of ES2022 syntax, but using ES2021 globals.

Currently, the `ecmaVersion` is set to `latest`, which currently evaluates to `es2022`: https://github.com/react-hookz/eslint-config/blob/7b6633ff777d4e79b0dcecd01d6972a546a7ae11/base.js#L10

Is this just me or can anybody else reproduce this? Would be happy to attempt crafting a PR for this, if this indeed is a problem for others also.

**Comment by xobotyi** [comment]
It is weird since this issue have been fixed like 3 months ago.
Also i've never faced it🤔

**Comment by ArttuOll** [comment]
Thanks for your reply, will try with the new version.

Weirdly, using my work computer the script runs just fine. Maybe my Yarn is outdated or there's something else wrong with my environment on the other machine. Anyway, clearly this problem exists only in my end, so I will close this issue.
